### ISSUE TITLE
Updates for ARM architecture?

### ISSUE THREAD

**Issue by Lewatoto** [flathub/org.qgis.qgis#94]
Thanks for the amazing job! There's any way to get a version above 3.4? I'm trying to run qgis on headless Raspbian GNU/Linux 10 (buster), and the remote-info show this:
```
pi@raspberry:~ $ flatpak remote-info --log flathub org.qgis.qgis
        ID: org.qgis.qgis
       Ref: app/org.qgis.qgis/arm/stable
      Arch: arm
    Branch: stable
Collection: org.flathub.Stable
  Download: 282.8 MB
 Installed: 790.8 MB
   Runtime: org.kde.Platform/arm/5.11

       Sdk: org.kde.Sdk/arm/5.11
    Commit: ace614575786f9e1fe216e6fb4c5e6ee1a7c490da9d598961a62ecfcab2599e2
    Parent: 4806887f4dd3bcbcd510e2ecc1b362570aa1b680f8d545f16801dc8beb088bec
   Subject: Added netcdf and hdf5 support (cdf2875c)
      Date: 2019-02-14 06:01:56 +0000
   History: 

    Commit: 4806887f4dd3bcbcd510e2ecc1b362570aa1b680f8d545f16801dc8beb088bec
   Subject: Update to qgis 3.4.2 (9ee661f8)
      Date: 2018-11-29 04:28:13 +0000

    Commit: 5e84c74785482325a2c3c8b985f48226e98c551321780d23b14cf658e8ff39fa
   Subject: Fix typo (1ce68a18)
      Date: 2018-11-07 08:18:18 +0000

    Commit: 12267ad29e4fd6d4651b9299a6a9462358a7fe85248c8e922afe81fcc5bcabcb
   Subject: Include -DWITH_3D=TRUE as suggested (3a2d3a83)
      Date: 2018-09-26 15:47:23 +0000

    Commit: 4dad716e7cf6b6de8bdfa277de6c629ea57f38d46bc77d56aa071af47629dfed
   Subject: Allow QGIS to access the network (92e56b48)
      Date: 2018-09-26 14:30:53 +0000

``` 
The reason why need a version above 3.4 is i'm trying to use the standalone console tool for running processing algorithms (https://changelog.qgis.org/en/qgis/version/3.14/#new-standalone-console-tool-for-running-processing)

I would appreciate any advice.
